name: lapse
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  cloud_firestore: ^6.1.1
  equatable: ^2.0.7
  firebase_auth: ^6.1.3
  firebase_core: ^4.3.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.0
  fpdart: ^1.2.0
  go_router: ^17.0.1
  google_fonts: ^6.3.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  lucide_icons: ^0.257.0
  moon_design: ^1.1.0
  uuid: ^4.5.2
  flutter_svg: ^2.1.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
